# Generated by Django 4.2.14 on 2024-07-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_album_artist_alter_artist_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='track',
            field=models.ManyToManyField(related_name='Playlists', to='music.track'),
        ),
    ]
